### ISSUE TITLE
Is this package a long-term project?

### ISSUE THREAD

**Issue by waynelapierre** [maxmouchet/ClickHouse.jl#1]
I would like to know if this package is a long-term project. It seems to have remained version 0.1 for a while. I am thinking about using this package for some projects.

**Comment by maxmouchet** [comment]
Hi,

This package is a [_very_](https://github.com/maxmouchet/ClickHouse.jl/blob/master/src/core.jl#L34-L51) simple client for the HTTP interface of ClickHouse.
Unless this interface change, the package should keep working :-)

I don't intend to add new features by myself, but if someone submit an issue / PR, or wants to maintain the package, I will look into it.

I haven't tried it, but there is another library that implements the TCP interface of ClickHouse: https://github.com/athre0z/ClickHouse.jl

Maxime

**Comment by waynelapierre** [comment]
thanks for your advice. it seems the two packages have the same name...

**Comment by maxmouchet** [comment]
Indeed, but they are not registered on the `General` Julia registry.
This is one is registered on my own registry:
```bash
pkg> registry add https://github.com/maxmouchet/JuliaRegistry.git
pkg> add ClickHouse
```
