### ISSUE TITLE
Cannot query Clickhouse DB

### ISSUE THREAD

**Issue by HiramTheHero** [maxmouchet/ClickHouse.jl#2]
When I run a query on a database:
```
df = query(client, "select applicant_income_000s, loan_amount_000s from lar_2004_2013")
```

I get the following error:
```
ERROR: ArgumentError: provide a valid sink argument, like `using DataFrames; CSV.read(source, DataFrame)`
```

Any idea what would be causing the issue?

Thank you for the package. I look forward to using it.

**Comment by maxmouchet** [comment]
Hi,

Indeed the package seems to be not working with recent CSV.jl versions.
Unfortunately I do not have the time to maintain this package anymore, but you can check other packages such as https://github.com/JuliaDatabases/ClickHouse.jl.
